version: "3.7"
services:
  aria2-pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - RPC_SECRET=P3TERX
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - TZ=Asia/Shanghai
      - SPECIAL_MODE=rclone
      - CUSTOM_TRACKER_URL=https://trackerslist.com/all_aria2.txt
    volumes:
      - ${PWD}/aria2-config:/config
      - ${PWD}/aria2-downloads:/downloads
# If you use host network mode, then no port mapping is required.
# This is your best choice when using IPv6.
    network_mode: host
#    ports:
#      - 6800:6800
#      - 6888:6888
#      - 6888:6888/udp
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
# AriaNg is just a static web page, usually you only need to deploy on a single host.
  ariang:
    container_name: ariang
    image: p3terx/ariang
    network_mode: bridge
    ports:
      - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
# telegram-bot setting
  tele-aria2:
    container_name: tele-aria2
    image: p3terx/tele-aria2
    network_mode: host
    volumes:
    - ${PWD}/.tele-aria2-conf.json:/config.json
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
